### ISSUE TITLE
提交不见了？

### ISSUE THREAD

**Issue by yujincheng08** [fullcone-nat-nftables/openwrt-firewall4-with-fullcone#3]
https://github.com/fullcone-nat-nftables/openwrt-firewall4-with-fullcone/commit/aa3b56e289fba7425e649a608c333622ffd9c367 不在 master 分支上

**Comment by yujincheng08** [comment]
我自己 merge 了一下： 74f767973bec0f049f17c01f0bd81ad6bf0e91d8

**Comment by wongsyrone** [comment]
近期在思考firewall4分开处理v4和v6的流量，但还没空写

**Comment by yujincheng08** [comment]
OK

**Comment by wongsyrone** [comment]
https://github.com/fullcone-nat-nftables/openwrt-firewall4-with-fullcone/commit/d4081c498ddca184578903fe5199d390bbc0707b
